### ISSUE TITLE
Issue with STM POS58 Thermal

### ISSUE THREAD

**Issue by wmxvi** [receipt-print-hq/chrome-raw-print#14]
Hi I've added the STMicroelectronics POS58 thermal printer to the manifest by
converting the hex codes to decimal using {"vendorId": 1110, "productId": 2056}

The printer appears in the list which is great, however when I try to print I see 

index.html:1 Unchecked runtime.lastError while running usb.bulkTransfer: Transfer failed.
    at printDataToInterface (chrome-extension://acjemkoimcgbcfmfilmclgakhlnkidkd/index.js:84:14)
    at Object.callback (chrome-extension://acjemkoimcgbcfmfilmclgakhlnkidkd/index.js:72:5)

In the console.

I'm not sure exactly what the issue is. I'm using OSX Sierra with the latest build of Google Chrome

**Comment by mike42** [comment]
I'll assume this is a bug.
